# Generated by Django 4.1.4 on 2023-03-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usd_to_inr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdp_in_us_dollar',
            name='gdp_usd',
            field=models.FloatField(),
        ),
    ]
